#!/bin/bash

declare -A PATHS
PATHS[alacritty]="${HOME}/.config/alacritty"
PATHS[bashrc]="${HOME}/.bashrc"
PATHS[neovim]="${HOME}/.config/nvim"
PATHS[vim]="${HOME}/.vimrc"
PATHS[vscode]="${HOME}/.config/Code - OSS/User/settings.json"
PATHS[qutebrowser]="${HOME}/.config/qutebrowser/autoconfig.yml"
PATHS[xinitrc]="${HOME}/.xinitrc"

sync() {
  for CFG in "${!PATHS[@]}"; do
    P="${PATHS[${CFG}]}"
    if [ -d "$P" ]; then
      cp -rv "$P" "dotfiles/"
    elif [ -f "$P" ]; then
      cp -rv "$P" "dotfiles/${CFG}"
    else
      rm -rf "dotfiles/${CFG}"
    fi
  done
}

install() {
  for CFG in "${!PATHS[@]}"; do
    cp -rv "dotfiles/${CFG}" "${PATHS[$CFG]}"
  done
}

$1
